# When releasing to crates.io:
#
# - last check for all TODO, FIXME, expect, unwrap.
# - re-read and final polish of documentation
# - run cargo udeps
# - run cargo clippy
# - recheck log statements (informative, none left that were just for development, ...)
# - Update CHANGELOG.md.
# - Update version numbers in Cargo.yml, Cargo.toml, install section of readme.
# - verify CI result
# - run cargo test on dependent crates
# - cargo publish
# - merge dev branch into master
# - create git tag with version number
#
[package]
name = "sweetch-bot"
version = "0.1.0"
authors = ["Bartosz Zbytniewski <bartosz.zbytniewski.dev@gmail.com>"]
edition = "2018"
description = ""
repository = "https://github.com/devzbysiu/sweetch-bot"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = []
categories = []
homepage = ""
documentation = ""

[dependencies]
anyhow = "1.0.32"
notify-rust = "4.0.0"
clokwerk = "0.3.3"
daemonize = "0.4.1"
log = "0.4.11"
pretty_env_logger = "0.4.0"
ureq = { version =  "1.4.1", features = ["json"] }
serde = { version = "1.0.116", features = ["derive"] }
